version: '3.7'

services:

  dashboard:
    image: sbdi/dashboard-dev
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./sbdi/data/config/dashboard-config.properties:/data/dashboard/config/dashboard-config.properties
